import 'package:awesome_notifications/awesome_notifications.dart';
import 'package:flutter/material.dart';
import 'package:mo3een/core/helpers/permission_helper.dart';

abstract class AppNotifyHelper {
  static initNotify() async {
    AwesomeNotifications().initialize(
      null,
      [
        NotificationChannel(
          channelKey: 'basic_channel',
          channelName: 'Basic notifications',
          channelDescription: 'Notification channel for basic tests',
          defaultColor: const Color(0xFF9D50DD),
          ledColor: Colors.white,
          soundSource: 'resource://raw/el7aram',
        )
      ],
    );
  }

  static sendNotify() {
    AwesomeNotifications().createNotification(
      content: NotificationContent(
        id: 10,
        channelKey: 'basic_channel',
        title: 'Hello Awesome Notifications!',
        body:
            'This is a simple notification generated by the Flutter app to test the package',
        customSound: 'resource://raw/el7aram',
      ),
    );
  }

  static sendNotifyInSpecificTime({required int id,required int hour,required int minute,required String timeZone}) {
    AppPermissionHelper.checkNotifyPermission().then((value) async{
      if(!value){
        await AwesomeNotifications().isNotificationAllowed().then((isAllowed) {
          if (!isAllowed) {
            AwesomeNotifications().requestPermissionToSendNotifications();
          }
        });
      }
      else{
        AwesomeNotifications().createNotification(
          content: NotificationContent(
            id: id,
            channelKey: 'basic_channel',
            title: 'Hello Awesome Notifications!',
            body:
            'This is a simple notification generated by the Flutter app to test the package',
            customSound: 'resource://raw/el7aram',
            criticalAlert: true,
            displayOnBackground: true,
            displayOnForeground: true,
            wakeUpScreen:true,
          ),
          schedule: NotificationCalendar(
            allowWhileIdle: true,
            hour: hour,
            minute: minute,
            repeats: true,
            timeZone: timeZone,
          ),
        );
      }
    });
  }
}
